### ISSUE TITLE
Frontiernav segment... missing

### ISSUE THREAD

**Issue by fredg1** [jahed/frontiernav#10]
i bet you're happy that you've completed the segments, and we sure are... until i discovered one was missing. The lower left segment of sylvalum is missing, is it normal? i wouldn't make a big alert out of this but since you said you were glad you finished the segments, i was worried (sorry for the missinformation i pressed enter after the title by accident)

**Comment by jahed** [comment]
You'll need to provide more info than that!

**Comment by fredg1** [comment]
the segment is diagonally left from FN site 403

**Comment by jahed** [comment]
Got it. Looks like I messed up some of the segments after migrating to a new data structure.

**Comment by jahed** [comment]
This should be fixed now. Thanks for pointing it out!

To reply to your edit: I thought I finished adding all the segments (excluding fast travels) but there's too many count... 😨 I appreciate all the help I can get.
