### ISSUE TITLE
Facebook login issues

### ISSUE THREAD

**Issue by FernandoDonati** [jahed/frontiernav#9]
Hey @jahed, first of all, excellent work! Your project is absolutely fantastic! 

One thing though is that when I try to login using facebook, it just goes back to the page unaltered (after fb authentication). Then, when I try to refresh the page, it just says "Checking if you're logged in...".
I tested it on Firefox and MS Edge. Clearing cache and deleting cookies doesn't seem to help. I managed to test the other login methods using incognito navigation and they both work great on both browsers.

Cheers,
Fernando

**Comment by jahed** [comment]
Thanks for reporting. Looks like a bug when creating new accounts.

**Comment by jahed** [comment]
Heh. Fixed. The bug was that the user's display name is limited to 20 characters. Facebook logins default to the full name, in your case that's 24 characters. I've increased the limit. Should work now.
